### ISSUE TITLE
Feature backlog

### ISSUE THREAD

**Issue by hsablonniere** [hsablonniere/hsablonniere.com#12]
This is the feature backlog for the site, a list of ideas and stuffs and I want to try and experiment.
It could contain ideas about the content structure but not about article ideas.

I may directly check stuffs once they're done but I also may create dedicated issues if necessary:

* [x] robots.txt
* [x] Favicon and other icons
* [x] Simple Web manifest
* [x] Open Graph meta tags #11
* [x] Open Graph image generation #11
* [x] Other "SEO" stuffs (description, author, canonical URL...)
* [x] POSSE cross post on Dev.to and medium #18
* [x] Byte range requests support in hititipi (naive impl)
* [x] htmlnano configuration
* [x] Reading time https://www.npmjs.com/package/@11tyrocks/eleventy-plugin-emoji-readtime
* [ ] Sitemap
  * Do I need one?
* [ ] Byte range requests support in hititipi (real impl)
* [ ] cssnano configuration
* [ ] Responsive images
  * Is it related to resizing images that are too big?
* [ ] Image format alternatives (webp, avif...)
* [ ] Video format alternatives
* [ ] Optimize videos
* [x] anchors on headings
* [ ] Eleventy plugins investigation
* [ ] posthtml plugins investigation
* [ ] experiment asciidoc
* [ ] Grammar, spellcheck, linting text...
* [ ] New design (with design system)
* [ ] design system https://kleinfreund.de/style-guide/
* [ ] Rename article task
* [ ] Create article task
* [ ] Preview app CI setup
* [ ] Publication scheduler
* [ ] Disable absolute URLs in Parcel
* [ ] Tags on contents
* [ ] Notes
* [ ] check links (canonical)
* [ ] Add list of talks
* [ ] Add resume
* [ ] Add bio/about
* [ ] License?
* [ ] Search
* [ ] Lists
* [ ] Analytics
  * https://matomo.org/
  * https://goaccess.io/
  * http://www.awstats.org/
* [ ] RSS styled with XSL
  * https://lepture.com/feed.xml
  * https://lepture.com/en/2019/rss-style-with-xsl
  * https://www.xml.com/pub/a/2006/11/29/xslt-xml-pretty-printer.html
  * https://osric.com/chris/accidental-developer/2008/12/create-an-xsl-stylesheet-for-your-rss-or-atom-feeds/
* [ ] Investigate RSS updates (updated date, ID, cache invalidation...)
* Try text editors (not really a feature)
  * https://obsidian.md/
  * https://typora.io/
  * https://takesmartnotes.com/
  * https://zettlr.com/
* Invesigate parcel alternatives
  * https://github.com/assetgraph/assetgraph
  * https://hacks.mozilla.org/2020/10/to-eleventy-and-beyond/
* List conference proposals https://github.com/MylesBorins/conference-proposals
* List conference invitation questions

**Comment by hsablonniere** [comment]
Have a look at https://www.industrialempathy.com/posts/eleventy-high-performance-blog/

**Comment by nhoizey** [comment]
Please work on "anchors on headings", I wanted to share your section about Parcel 2… 😅

Hint… https://github.com/valeriangalliat/markdown-it-anchor

**Comment by hsablonniere** [comment]
@nhoizey You know what? I was working on a new article and I thought "hey, I should add anchors". I looked at pack11ty, then at your site. I shipped it and went here to tick my todo. Then I see your message :rofl:

https://www.hsablonniere.com/once-upon-a-blog--9849zg/#optimized-with-parcel-v2

**Comment by nhoizey** [comment]
That's an awesome coincidence! 🤗
